"""init

Revision ID: eaaef7b45b61
Revises: 
Create Date: 2022-05-04 13:20:30.215808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaef7b45b61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abisol_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abisol_members_email'), 'abisol_members', ['email'], unique=True)
    op.create_index(op.f('ix_abisol_members_username'), 'abisol_members', ['username'], unique=False)
    op.create_table('work_table_records',
    sa.Column('abisol_member_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('date_attribute', sa.String(length=64), nullable=True),
    sa.Column('late_early', sa.String(length=64), nullable=True),
    sa.Column('start_at', sa.String(length=64), nullable=True),
    sa.Column('end_at', sa.String(length=64), nullable=True),
    sa.Column('working_hour', sa.String(length=64), nullable=True),
    sa.Column('recess_hour', sa.String(length=64), nullable=True),
    sa.Column('extra_hour', sa.String(length=64), nullable=True),
    sa.Column('graveyard_shift_hour', sa.String(length=64), nullable=True),
    sa.Column('holiday_shift_hour', sa.String(length=64), nullable=True),
    sa.Column('work_content', sa.String(length=128), nullable=True),
    sa.Column('about_attendance', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['abisol_member_id'], ['abisol_members.id'], ),
    sa.PrimaryKeyConstraint('abisol_member_id', 'year', 'month', 'day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_table_records')
    op.drop_index(op.f('ix_abisol_members_username'), table_name='abisol_members')
    op.drop_index(op.f('ix_abisol_members_email'), table_name='abisol_members')
    op.drop_table('abisol_members')
    # ### end Alembic commands ###
